DATABASE jdbc derby NAME Store

CREATE TABLE ARTICLE
(
ARTICLENAME VARCHAR(500) PRIMARY KEY NOT NULL,
ARTICLEVALUE DOUBLE NOT NULL,
ARTICLEUNIT CHAR(5) NOT NULL,
ARTICLEPRICE DOUBLE NOT NULL,
ARTICLECURRENCY CHAR(5) NOT NULL,
TOTALPRICE DOUBLE NOT NULL
)

CREATE TABLE DAILYDELIVERY
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
DATEADDED VARCHAR(20) NOT NULL,
ARTICLENAME VARCHAR(500) NOT NULL,
ARTICLEVALUE DOUBLE NOT NULL,
ARTICLEUNIT CHAR(5) NOT NULL,
ARTICLEPRICE DOUBLE NOT NULL,
ARTICLECURRENCY CHAR(5) NOT NULL,
TOTAL DOUBLE NOT NULL,
UNIQUE (ID)
)

CREATE TABLE DAILYSALE
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
DATEADDED VARCHAR(20) NOT NULL,
ARTICLENAME VARCHAR(500) NOT NULL,
ARTICLEVALUE DOUBLE NOT NULL,
ARTICLEUNIT CHAR(5) NOT NULL,
ARTICLEPRICE DOUBLE NOT NULL,
ARTICLECURRENCY CHAR(5) NOT NULL,
TOTAL DOUBLE NOT NULL,
UNIQUE (ID)
)

CREATE TABLE USERPAYMENT
(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
ARTICLENAME VARCHAR(500) NOT NULL,
ARTICLEVALUE DOUBLE NOT NULL,
ARTICLEUNIT CHAR(5) NOT NULL,
ARTICLEPRICE DOUBLE NOT NULL,
ARTICLECURRENCY CHAR(5) NOT NULL,
TOTAL DOUBLE NOT NULL,
UNIQUE (ID)
)
